# Generated by Django 5.2.14 on 2026-05-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('starting_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('goal', models.CharField(blank=True, choices=[('weight_loss', 'Dimagrimento'), ('maintenance', 'Mantenimento'), ('muscle_gain', 'Massa muscolare'), ('performance', 'Performance')], max_length=32)),
                ('activity_level', models.CharField(blank=True, choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta')], max_length=16)),
                ('dietary_preferences', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
