# Generated by Django 5.2.14 on 2026-05-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('calories_per_100g', models.PositiveIntegerField(default=0)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Colazione'), ('lunch', 'Pranzo'), ('dinner', 'Cena'), ('snack', 'Snack')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
        ),
    ]
