# Generated by Django 5.2.14 on 2026-05-10 15:13

import django.db.models.deletion
import running.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='activity_file',
            field=models.FileField(blank=True, upload_to='running/%Y/%m/', validators=[running.models.validate_activity_file]),
        ),
        migrations.CreateModel(
            name='RunTrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('seconds_from_start', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='running.run')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
