# Generated by Django 5.2.14 on 2026-05-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('fruit', 'Frutta'), ('vegetables', 'Verdura'), ('protein', 'Proteine'), ('grains', 'Cereali'), ('dairy', 'Latticini'), ('other', 'Altro')], default='other', max_length=24)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('is_bought', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_bought', 'category', 'name'],
            },
        ),
    ]
